"""empty message

Revision ID: 3b981f7e2c5b
Revises: 5d9a2c4de0eb
Create Date: 2020-12-22 17:37:56.083390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b981f7e2c5b'
down_revision = '5d9a2c4de0eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.drop_column('comment', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('image_file', sa.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'post_id')
    # ### end Alembic commands ###
